### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by raderio** [konform-kt/konform#12]
No changes since last year.

**Comment by nlochschmidt** [comment]
Maintainer here: I am planning to continue to work on konform if there is sufficient interest in the project. I am myself not using it professionally at the moment since we are using a [full JSON schema validator](https://github.com/everit-org/json-schema/) for our backend instead.

I am hopeful that this project has value to people, since it is fairly easy to extend without me having to change the library directly.
