### ISSUE TITLE
Additional maintainers?..

### ISSUE THREAD

**Issue by kibertoad** [konform-kt/konform#32]
Hi! We are considering using Konform in our company, but are slightly concerned with decreased velocity of the project lately. Would you be open to accepting new maintainers to ensure the long-term continuity of the project?

**Comment by andrewliles** [comment]
I am up for helping.  We're making intensive used of it for 4 months and find it very stable and don't yet find any shortcomings.

Also, we have some integrations with Spring that might make a nice HOWTO article if you'd be interested Niklas.

**Comment by nlochschmidt** [comment]
Hey there, as I wrote in #38 I am not opposed to the idea of adding (co-)maintainers to this project.

**Comment by nlochschmidt** [comment]
@jillesvangurp could you please open a separate issue for the dependency upgrade that you require? I am currently working on upgrading to Kotlin 1.6 anyways. Otherwise, this project has no dependencies that would need upgrading 🤷 

I've been waiting for responses in the issues related to the MRs but I might just go ahead and merge them this week since there doesn't seem to be a response coming 😉

**Comment by jillesvangurp** [comment]
Great, an upgrade to 1.6 is actually what I need. Let me know if you need help with that.

**Comment by nlochschmidt** [comment]
@dhoepelman has joined as a maintainer and we have transitioned into a handover period, see https://github.com/konform-kt/konform/discussions/38#discussioncomment-8951572 and https://github.com/konform-kt/konform/issues/79#issuecomment-2027194364

I am closing this issue to have the issue tracker clear, but feel free to respond below if you are still interested in becoming an additional maintainer.
