### ISSUE TITLE
How to validate single values?

### ISSUE THREAD

**Issue by amr** [konform-kt/konform#54]
For example, how to create a validation for a `String` or `LocalDate`? without having them part of some other object

I was able to achieve by dropping to `addConstraint`:

```kotlin
va validation = Validation<String?> {
    addConstraint("must be 4 digits") { it != null && it.length == 4 }
}
```

but wasn't unable to utilize `required`, `ifPresent` or any of the existing validators (`minLength`, ...etc).

Is that supported?

**Comment by nlochschmidt** [comment]
Just to be clear. You are asking specifically about validating nullable values like `String?` and `LocalDate?` correct?

Because non-nullables work, e.g.

```kotlin
val validatePassword = Validation<String> {
    minLength(8)
}
```

I believe it is currently not possible to validate nullable in a nice way. Good catch.

I guess we could do either something like

```kotlin
Validation<String?>.ifPresent {
    minLength(8)
}
```

Or probably better

```kotlin
Validation<String?> {
    ifPresent {
       minLength(8)
    }
}
```

**Comment by amr** [comment]
Yep that's accurate, both suggested versions look great to me
